// ─── PhotoBooth Pro: Sticker Definitions ─────────────────────────────────────
// Stickers from https://github.com/amirisback/photo-panda-bear-dudu-bubu

export interface StickerDef {
  id: string;
  label: string;
  src: string; // path relative to /stickers/
  category: "bear" | "panda" | "couple" | "dudu-bubu";
}

// ── Helper to auto-generate label from filename ──────────────────────────────
function s(file: string, category: StickerDef["category"]): StickerDef {
  const name = file.replace(/\.gif$/, "").replace(/^(bear-panda-|bear-|panda-)/, "");
  const label = name.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  return { id: file.replace(/\.gif$/, ""), label, src: `/stickers/${file}`, category };
}

function sc(file: string): StickerDef {
  const name = file.replace(/\.gif$/, "").replace(/^bear-panda-/, "");
  const label = name.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  return { id: `couple-${file.replace(/\.gif$/, "")}`, label, src: `/stickers/couple/${file}`, category: "couple" };
}

// ── Dudu & Bubu originals ────────────────────────────────────────────────────
const duduBubuStickers: StickerDef[] = [
  { id: "bubu-happy", label: "Bubu Happy", src: "/stickers/bubu-happy.gif", category: "dudu-bubu" },
  { id: "bubu-walk", label: "Bubu Walk", src: "/stickers/bubu-walk.gif", category: "dudu-bubu" },
  { id: "bubu-eat", label: "Bubu Eat", src: "/stickers/bubu-eat.gif", category: "dudu-bubu" },
  { id: "dudu-walk", label: "Dudu Walk", src: "/stickers/dudu-walk.gif", category: "dudu-bubu" },
  { id: "dudu-eat", label: "Dudu Eat", src: "/stickers/dudu-eat.gif", category: "dudu-bubu" },
];

// ── Bear (Dudu) stickers ─────────────────────────────────────────────────────
const bearStickers: StickerDef[] = [
  s("bear-angry.gif", "bear"),
  s("bear-annoy.gif", "bear"),
  s("bear-annoying-joget-cd.gif", "bear"),
  s("bear-annoying.gif", "bear"),
  s("bear-background-sok-imut.gif", "bear"),
  s("bear-bajunya-ga-bener.gif", "bear"),
  s("bear-bajunya-miring.gif", "bear"),
  s("bear-banyak-uang.gif", "bear"),
  s("bear-bawa-palu-balon.gif", "bear"),
  s("bear-bawa-tisue-toilet.gif", "bear"),
  s("bear-bayi-kelaparan-01.gif", "bear"),
  s("bear-bayi-kelaparan.gif", "bear"),
  s("bear-bentak-meja.gif", "bear"),
  s("bear-berdiri-di-tebing.gif", "bear"),
  s("bear-berendam-air-panas.gif", "bear"),
  s("bear-blink-2.gif", "bear"),
  s("bear-blink.gif", "bear"),
  s("bear-box.gif", "bear"),
  s("bear-bring-flower.gif", "bear"),
  s("bear-chick-love.gif", "bear"),
  s("bear-chick.gif", "bear"),
  s("bear-chicken-egg.gif", "bear"),
  s("bear-chicken.gif", "bear"),
  s("bear-chubby.gif", "bear"),
  s("bear-clown.gif", "bear"),
  s("bear-coach.gif", "bear"),
  s("bear-cosplay-gyoza.gif", "bear"),
  s("bear-cosplay-jadi-lebah.gif", "bear"),
  s("bear-cosplay-moci.gif", "bear"),
  s("bear-dancing.gif", "bear"),
  s("bear-dicium-pipinya.gif", "bear"),
  s("bear-didulang.gif", "bear"),
  s("bear-dinosaur.gif", "bear"),
  s("bear-dipukpuk.gif", "bear"),
  s("bear-donat.gif", "bear"),
  s("bear-drink-boba.gif", "bear"),
  s("bear-duck.gif", "bear"),
  s("bear-easy-walk.gif", "bear"),
  s("bear-eat.gif", "bear"),
  s("bear-eating-strawberry.gif", "bear"),
  s("bear-eit-tidak-boleh.gif", "bear"),
  s("bear-elus-panda-sampe-tidur.gif", "bear"),
  s("bear-emmm.gif", "bear"),
  s("bear-emosi-buang-dotX.gif", "bear"),
  s("bear-fan.gif", "bear"),
  s("bear-funny-dancing-02.gif", "bear"),
  s("bear-funny-dancing.gif", "bear"),
  s("bear-ganbate-bisa.gif", "bear"),
  s("bear-garuk-bokong.gif", "bear"),
  s("bear-goyang-bando-bintang.gif", "bear"),
  s("bear-happy-dancing-self.gif", "bear"),
  s("bear-idle-position-01.gif", "bear"),
  s("bear-idle-position-02.gif", "bear"),
  s("bear-idle-position-03.gif", "bear"),
  s("bear-jacket.gif", "bear"),
  s("bear-jadi-dino.gif", "bear"),
  s("bear-jalan.gif", "bear"),
  s("bear-jerapah-01.gif", "bear"),
  s("bear-jerapah.gif", "bear"),
  s("bear-jualan-semangka.gif", "bear"),
  s("bear-kacamata.gif", "bear"),
  s("bear-kaos-kaki-bau.gif", "bear"),
  s("bear-kenyang.gif", "bear"),
  s("bear-keranjang-belanja.gif", "bear"),
  s("bear-kissed.gif", "bear"),
  s("bear-knock-knock.gif", "bear"),
  s("bear-lari-bawa-boba.gif", "bear"),
  s("bear-maen-bulu-tanaman.gif", "bear"),
  s("bear-maen-dokter.gif", "bear"),
  s("bear-maen-hp-mengkurep.gif", "bear"),
  s("bear-maen-piano.gif", "bear"),
  s("bear-makan-biskuit-belepotan.gif", "bear"),
  s("bear-makan-biskuit-besar-lucu.gif", "bear"),
  s("bear-makan-nasi-1-rice-cooker.gif", "bear"),
  s("bear-makan-permen-karet.gif", "bear"),
  s("bear-makan-popmie.gif", "bear"),
  s("bear-makan-salju.gif", "bear"),
  s("bear-makan.gif", "bear"),
  s("bear-masuk-kulkas.gif", "bear"),
  s("bear-mecucu.gif", "bear"),
  s("bear-mega-phone.gif", "bear"),
  s("bear-menunjuk.gif", "bear"),
  s("bear-mikir.gif", "bear"),
  s("bear-minta-cium-pipi.gif", "bear"),
  s("bear-minum-boba-ditaman.gif", "bear"),
  s("bear-minum-softdrink.gif", "bear"),
  s("bear-mulet.gif", "bear"),
  s("bear-naek-mobil-mainan.gif", "bear"),
  s("bear-nahan-emosi.gif", "bear"),
  s("bear-nangis.gif", "bear"),
  s("bear-ngambul.gif", "bear"),
  s("bear-ngupil.gif", "bear"),
  s("bear-nindihin-panda-pas-rebahan.gif", "bear"),
  s("bear-nonton-netflix.gif", "bear"),
  s("bear-okwe-yes.gif", "bear"),
  s("bear-opname-maen-hp.gif", "bear"),
  s("bear-persiapan-tidur.gif", "bear"),
  s("bear-play-guitar.gif", "bear"),
  s("bear-play-laptop.gif", "bear"),
  s("bear-push-up-cium.gif", "bear"),
  s("bear-puyeng-dibantal.gif", "bear"),
  s("bear-ready-for-run.gif", "bear"),
  s("bear-rebahan-kupu-kupu.gif", "bear"),
  s("bear-rope.gif", "bear"),
  s("bear-scare-wall.gif", "bear"),
  s("bear-scooter.gif", "bear"),
  s("bear-senyum-lebar.gif", "bear"),
  s("bear-shock-chair.gif", "bear"),
  s("bear-skipping.gif", "bear"),
  s("bear-study.gif", "bear"),
  s("bear-suka-dicium-dipipi.gif", "bear"),
  s("bear-super-kawai.gif", "bear"),
  s("bear-super.gif", "bear"),
  s("bear-swing.gif", "bear"),
  s("bear-table-tennis.gif", "bear"),
  s("bear-take-mirror.gif", "bear"),
  s("bear-tembakan-cinta-biu.gif", "bear"),
  s("bear-terbang-gara-gara-balon.gif", "bear"),
  s("bear-terkejoed.gif", "bear"),
  s("bear-wizard.gif", "bear"),
];

// ── Panda (Bubu) stickers ────────────────────────────────────────────────────
const pandaStickers: StickerDef[] = [
  s("panda-angry.gif", "panda"),
  s("panda-annoy.gif", "panda"),
  s("panda-annoying-joget-cd.gif", "panda"),
  s("panda-annoying.gif", "panda"),
  s("panda-background-sok-imut.gif", "panda"),
  s("panda-bajunya-ga-bener.gif", "panda"),
  s("panda-bajunya-ga-muat.gif", "panda"),
  s("panda-bajunya-miring.gif", "panda"),
  s("panda-banyak-uang.gif", "panda"),
  s("panda-bawa-palu-balon.gif", "panda"),
  s("panda-bawa-tisue-toilet.gif", "panda"),
  s("panda-bayi-kelaparan-01.gif", "panda"),
  s("panda-bayi-kelaparan.gif", "panda"),
  s("panda-bentak-meja.gif", "panda"),
  s("panda-berdiri-di-tebing.gif", "panda"),
  s("panda-berendam-air-panas.gif", "panda"),
  s("panda-bingung-milih-baju.gif", "panda"),
  s("panda-bingung.gif", "panda"),
  s("panda-blink-2.gif", "panda"),
  s("panda-blink.gif", "panda"),
  s("panda-box.gif", "panda"),
  s("panda-bring-flower.gif", "panda"),
  s("panda-chick-love.gif", "panda"),
  s("panda-chick.gif", "panda"),
  s("panda-chicken-egg.gif", "panda"),
  s("panda-chicken.gif", "panda"),
  s("panda-chubby.gif", "panda"),
  s("panda-clown.gif", "panda"),
  s("panda-coach.gif", "panda"),
  s("panda-cosplay-gyoza.gif", "panda"),
  s("panda-cosplay-jadi-lebah.gif", "panda"),
  s("panda-cosplay-moci.gif", "panda"),
  s("panda-dancing.gif", "panda"),
  s("panda-dicium-pipinya.gif", "panda"),
];

// ── Couple stickers ──────────────────────────────────────────────────────────
const coupleStickers: StickerDef[] = [
  sc("bear-pada-maen-mesin-doll-01.gif"),
  sc("bear-pada-maen-mesin-doll-02.gif"),
  sc("bear-panda-annoying-01.gif"),
  sc("bear-panda-annoying-02.gif"),
  sc("bear-panda-annyoing-dance.gif"),
  sc("bear-panda-cat-dancing.gif"),
  sc("bear-panda-ciluk-ba.gif"),
  sc("bear-panda-cilukba.gif"),
  sc("bear-panda-cipika-cipiki.gif"),
  sc("bear-panda-ciuman-01.gif"),
  sc("bear-panda-ciuman-02.gif"),
  sc("bear-panda-clothes.gif"),
  sc("bear-panda-colek-pipi-01.gif"),
  sc("bear-panda-colek-pipi-02.gif"),
  sc("bear-panda-couple-love-jokes.gif"),
  sc("bear-panda-couple-photos.gif"),
  sc("bear-panda-couple.gif"),
  sc("bear-panda-cow-dancing-01.gif"),
  sc("bear-panda-cow-dancing-02.gif"),
  sc("bear-panda-cupcup-ngalem-01.gif"),
  sc("bear-panda-cupcup-ngalem-02.gif"),
  sc("bear-panda-dance-giraffe.gif"),
  sc("bear-panda-dancing-together-fun.gif"),
  sc("bear-panda-dancing-together.gif"),
  sc("bear-panda-dicium-pipi-malu-01.gif"),
  sc("bear-panda-dicium-pipi-malu-02.gif"),
  sc("bear-panda-digendong-bear-ketiduran.gif"),
  sc("bear-panda-dipukpuk-mendal-01.gif"),
  sc("bear-panda-dipukpuk-mendal-02.gif"),
  sc("bear-panda-double-blink.gif"),
  sc("bear-panda-eat-together-fun.gif"),
  sc("bear-panda-eating-ramen-01.gif"),
  sc("bear-panda-eating-ramen-02.gif"),
  sc("bear-panda-eating-water-melon-01.gif"),
  sc("bear-panda-eating-water-melon-02.gif"),
  sc("bear-panda-elus-kening-01.gif"),
  sc("bear-panda-elus-kening-02.gif"),
  sc("bear-panda-fridge.gif"),
  sc("bear-panda-gendut.gif"),
  sc("bear-panda-give-flower.gif"),
  sc("bear-panda-goyang-pake-topi-babi.gif"),
  sc("bear-panda-head-bang.gif"),
  sc("bear-panda-horse.gif"),
  sc("bear-panda-jadi-ketupat.gif"),
  sc("bear-panda-jadi-roti-coklat.gif"),
  sc("bear-panda-jas-hujan.gif"),
  sc("bear-panda-joget-disco.gif"),
  sc("bear-panda-jumping-01.gif"),
  sc("bear-panda-jumping-02.gif"),
  sc("bear-panda-kasih-makan-kucing.gif"),
  sc("bear-panda-kawai.gif"),
  sc("bear-panda-kegendutan.gif"),
  sc("bear-panda-loncat-loncat-seneng-01.gif"),
  sc("bear-panda-loncat-loncat-seneng-02.gif"),
  sc("bear-panda-loncatin-punggung-01.gif"),
  sc("bear-panda-loncatin-punggung-02.gif"),
  sc("bear-panda-maen-tali.gif"),
  sc("bear-panda-maenan-pipi-waktu-rebahan-01.gif"),
  sc("bear-panda-maenan-pipi-waktu-rebahan-02.gif"),
  sc("bear-panda-mancing-ikan.gif"),
  sc("bear-panda-mandi-bareng.gif"),
  sc("bear-panda-minta-cium-01.gif"),
  sc("bear-panda-minta-cium-02.gif"),
  sc("bear-panda-motor-blue.gif"),
  sc("bear-panda-nonton-video-dihp.gif"),
  sc("bear-panda-pelukpeluk-manja-01.gif"),
  sc("bear-panda-pelukpeluk-manja-02.gif"),
  sc("bear-panda-photo-selfie-kaca.gif"),
  sc("bear-panda-playing-laptop.gif"),
  sc("bear-panda-playing-phone-fun.gif"),
  sc("bear-panda-playing-phone.gif"),
  sc("bear-panda-potato.gif"),
  sc("bear-panda-rabbit-dancing.gif"),
  sc("bear-panda-rebahan-kipas.gif"),
  sc("bear-panda-ride-bear.gif"),
  sc("bear-panda-ride-music-01.gif"),
  sc("bear-panda-ride-music-02.gif"),
  sc("bear-panda-ride.gif"),
  sc("bear-panda-run.gif"),
  sc("bear-panda-scoouter.gif"),
  sc("bear-panda-scouter-one.gif"),
  sc("bear-panda-selfie-01.gif"),
  sc("bear-panda-selfie-02.gif"),
  sc("bear-panda-sleep-together-ngorok.gif"),
  sc("bear-panda-sleepy.gif"),
  sc("bear-panda-sok-jadi-preman-01.gif"),
  sc("bear-panda-sok-jadi-preman-02.gif"),
  sc("bear-panda-sok-ngambek-01.gif"),
  sc("bear-panda-sok-ngambek-02.gif"),
  sc("bear-panda-spining-jump-01.gif"),
  sc("bear-panda-spining-jump-02.gif"),
  sc("bear-panda-sport-1.gif"),
  sc("bear-panda-sport-2.gif"),
  sc("bear-panda-sport-3.gif"),
  sc("bear-panda-study-together.gif"),
  sc("bear-panda-swing-01.gif"),
  sc("bear-panda-swing.gif"),
  sc("bear-panda-tennis.gif"),
  sc("bear-panda-tiba-tiba-ndusel-01.gif"),
  sc("bear-panda-tiba-tiba-ndusel-02.gif"),
  sc("bear-panda-tickling.gif"),
  sc("bear-panda-tidur-bareng.gif"),
  sc("bear-panda-tidur-nyenyak.gif"),
  sc("bear-panda-tos-minum-dot.gif"),
  sc("bear-panda-walk-together.gif"),
  sc("bear-panda-wek.gif"),
];

// ── All stickers combined ────────────────────────────────────────────────────
export const stickers: StickerDef[] = [
  ...duduBubuStickers,
  ...bearStickers,
  ...pandaStickers,
  ...coupleStickers,
];

// ── Category labels for UI tabs ──────────────────────────────────────────────
export const stickerCategories = [
  { key: "all" as const, label: "All" },
  { key: "dudu-bubu" as const, label: "Dudu & Bubu" },
  { key: "bear" as const, label: "Bear (Dudu)" },
  { key: "panda" as const, label: "Panda (Bubu)" },
  { key: "couple" as const, label: "Couple 💕" },
] as const;

export type StickerCategoryKey = (typeof stickerCategories)[number]["key"];
